version: '2.3'

x-php: &php
  init: true
  depends_on:
    db:
      condition: service_healthy
    memcached:
      condition: service_started
    elasticsearch:
      condition: service_healthy
    xray:
      condition: service_started
    mailhog:
      condition: service_started
  image: humanmade/altis-local-server-php:3.2.0
  links:
    - "db:db-read-replica"
  external_links:
    - "proxy:${HTTP_HOST:-default}"
    - "proxy:pinpoint-${HTTP_HOST:-default}"
    - "proxy:cognito-${HTTP_HOST:-default}"
    - "proxy:elasticsearch-${HTTP_HOST:-default}"
  volumes:
    - "${VOLUME}:/usr/src/app:delegated"
    # Use zzz as a prefix to ensure the php.ini overrides are loaded last
    - "${PWD}/php.ini:/usr/local/etc/php/conf.d/zzz-vip.ini"
    - socket:/var/run/php-fpm
  networks:
    - proxy
    - default
  environment:
    COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME:-default}
    HOST_PATH: ${VOLUME}
    DB_HOST: db
    DB_READ_REPLICA_HOST: db-read-replica
    DB_PASSWORD: wordpress
    DB_NAME: wordpress
    DB_USER: wordpress
    WP_DEBUG: 1
    WP_DEBUG_DISPLAY: 0
    PAGER: more
    ENV_ARCHITECTURE: 'local-server'
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9200
    AWS_XRAY_DAEMON_HOST: xray
    PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    # Setting required for minimal config in PHPStorm
    PHP_IDE_CONFIG: serverName=${HTTP_HOST:-default}
    # Enables XDebug for all processes and allows setting remote_host externally for Linux support
    XDEBUG_CONFIG: idekey=${HTTP_HOST:-default} remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal}
    # Pass through subdomains configuration into PHP
    SUBDOMAIN_INSTALL: ${SUBDOMAIN_INSTALL}

x-analytics: &analytics
  ports:
    - "3000"
  networks:
    - proxy
    - default
  restart: unless-stopped

services:
  db:
    image: mysql:5.7
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "wordpress", "-pwordpress" ]
      timeout: 5s
      interval: 5s
      retries: 10

  memcached:
    image: memcached
    restart: always

  php:
    <<: *php
    image: ${PHP_IMAGE:-humanmade/altis-local-server-php:3.2.0}
    depends_on:
      - memcached

  nginx:
    image: humanmade/altis-local-server-nginx:3.1.0
    networks:
      - proxy
      - default
    depends_on:
      - php
    volumes:
      - "${VOLUME}:/usr/src/app:delegated"
      - socket:/var/run/php-fpm
    ports:
      - "8080"
    labels:
      - "traefik.frontend.priority=1"
      - "traefik.port=8080"
      - "traefik.protocol=https"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:${HTTP_HOST:-default},{subdomain:[a-z._-]+}.${HTTP_HOST:-default}"
  xray:
    image: amazon/aws-xray-daemon:3.0.1
    ports:
      - "2000"
    environment:
      AWS_ACCESS_KEY_ID: YOUR_KEY_HERE
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_HERE
      AWS_REGION: us-east-1

  cavalcade:
    <<: *php
    entrypoint:
      - /usr/local/bin/cavalcade
    user: "nobody:nobody"
    restart: unless-stopped

  elasticsearch:
    image: humanmade/altis-local-server-elasticsearch:3.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: ${ES_MEM_LIMIT:-1g}
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ${VOLUME}/wp-content/uploads/es-packages:/usr/share/elasticsearch/config/packages
    ports:
      - "9200"
    networks:
      - proxy
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 25
    labels:
      - "traefik.port=9200"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=HostRegexp:elasticsearch-${HTTP_HOST:-default}"
    environment:
      - http.max_content_length=10mb

      # Force ES into single-node mode (otherwise defaults to zen discovery as
      # network.host is set in the default config)
      - discovery.type=single-node

      # Reduce from default of 1GB of memory to 512MB
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025"
      - "1025"
    networks:
      - proxy
      - default
    labels:
      - "traefik.port=8025"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:${HTTP_HOST:-default};PathPrefix:/mailhog"
    environment:
      MH_UI_WEB_PATH: mailhog
  cognito:
    <<: *analytics
    image: humanmade/local-cognito:1.0.0
    labels:
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:cognito-${HTTP_HOST:-default}"

  pinpoint:
    <<: *analytics
    image: humanmade/local-pinpoint:1.2.2
    labels:
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:pinpoint-${HTTP_HOST:-default}"
    environment:
      INDEX_ROTATION: OneDay

  kibana:
    image: blacktop/kibana:6.3
    networks:
      - proxy
      - default
    ports:
      - "5601"
    labels:
      - "traefik.port=5601"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:${HTTP_HOST:-default};PathPrefix:/kibana"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ${PWD}/kibana.yml:/usr/share/kibana/config/kibana.yml

networks:
  default:
  proxy:
    external:
      name: proxy

volumes:
  db-data:
  es-data:
  tmp:
  socket:
